backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/images"
public_folder: "images"
publish_mode: editorial_workflow
collections:
  - name: "raw"
    label: "Old Layout"
    folder: "src/raw"
    create: true
    extension: html
    format: yaml-frontmatter
    preview_path: raw/{{slug}}
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/raw.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL slug", name: "permalink", widget: "string", required: false, hint: "Leave this blank to generate the URL automatically."}
      - { label: "templateEnginer", name: "templateEngineOverride", widget: "hidden", default: "md,njk"}
      - { label: "Parent page name", name: "parent_page", widget: "string"}
      - { label: "Parent page URL", name: "parent_page_link", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "rules"
    label: "Kinship caregiver rules"
    folder: "src/rules"
    create: false
    extension: html
    format: yaml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/raw.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL slug", name: "permalink", widget: "string", required: false, hint: "Leave this blank to generate the URL automatically."}
      - { label: "templateEnginer", name: "templateEngineOverride", widget: "hidden", default: "md,njk"}
      - { label: "Parent page name", name: "parent_page", widget: "string"}
      - { label: "Parent page URL", name: "parent_page_link", widget: "string"}
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Categories"
        name: "links"
        widget: "list"
        label_singular: "a category"
        fields:
          - label: "Section title"
            name: "sectionTitle"
            widget: "string"
          - label: "Pages"
            name: "items"
            widget: "list"
            label_singular: "a page"
            fields:
              - label: "Link title"
                name: "linkTitle"
                widget: "string"
              - label: "Link URL"
                name: "linkUrl"
                widget: "string"